In [8]:
import sys
! {sys.executable} -m pip install xlrd==2.0.1

Collecting xlrd==2.0.1
  Using cached xlrd-2.0.1-py2.py3-none-any.whl.metadata (3.4 kB)
Using cached xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1

In [17]:
import os
import pandas as pd
from IPython.display import display  # 专门用来交互显示

def read_china_sheets(folder_path):
    all_data = {}
    for file in os.listdir(folder_path):
        if file.endswith(".xlsx") or file.endswith(".xls"):
            file_path = os.path.join(folder_path, file)
            try:
                df = pd.read_excel(file_path, sheet_name="CHINA", header=1) 
                all_data[file] = df
                print(f"✅ 成功读取 {file} 中的 'CHINA' sheet")
            except Exception as e:
                print(f"⚠️ 跳过 {file}，原因: {e}")
    return all_data


if __name__ == "__main__":
    folder = r"D:\UN\02-UN DESA world urbanization prospects"
    china_sheets = read_china_sheets(folder)

    # 交互式展示所有文件
    if china_sheets:
        for file, df in china_sheets.items():
            print(f"\n📂 文件名: {file}")
            display(df.head())  # 交互式展示（带表格格式）
    else:
        print("❌ 没有读取到任何数据")

✅ 成功读取 WUP2018-F01-Total_Urban_Rural.xls 中的 'CHINA' sheet
✅ 成功读取 WUP2018-F02-Proportion_Urban.xls 中的 'CHINA' sheet
✅ 成功读取 WUP2018-F03-Urban_Population.xls 中的 'CHINA' sheet
✅ 成功读取 WUP2018-F04-Rural_Population.xls 中的 'CHINA' sheet
✅ 成功读取 WUP2018-F05-Total_Population.xls 中的 'CHINA' sheet

📂 文件名: WUP2018-F01-Total_Urban_Rural.xls

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,"Population of Urban and Rural Areas at Mid-Year (thousands) and Percentage Urban, 2018",Unnamed: 5,Unnamed: 6
0,Index,"Region, subregion, country or area",Note,Country\ncode,Urban,Rural,Total
1,79,China,4,156,837022.095,578023.833,1415045.928
2,80,"China, Hong Kong SAR",5,344,7428.887,0,7428.887
3,81,"China, Macao SAR",6,446,632.418,0,632.418
4,82,"China, Taiwan Province of China",NaN,158,18518.291,5175.798,23694.089

📂 文件名: WUP2018-F02-Proportion_Urban.xls

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,"Percentage of Population at Mid-Year Residing in Urban Areas, 1950-2050",Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,Index,"Region, subregion, country or area",Note,Country\ncode,1950.000,1955.000,1960.000,1965.000,1970.000,1975.000,...,2005.000,2010.000,2015.000,2020.000,2025.000,2030.000,2035.000,2040.000,2045.000,2050.000
1,79,China,4,156,11.803,13.856,16.203,18.086,17.400,17.400,...,42.522,49.226,55.500,61.428,66.481,70.626,73.918,76.436,78.318,80.028
2,80,"China, Hong Kong SAR",5,344,85.200,85.200,85.200,86.422,87.729,89.695,...,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000
3,81,"China, Macao SAR",6,446,96.890,96.169,95.289,96.177,97.032,97.891,...,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000,100.000
4,82,"China, Taiwan Province of China",NaN,158,26.842,29.074,31.412,33.857,36.484,39.784,...,72.292,74.687,76.916,78.942,80.770,82.406,83.858,85.149,86.350,87.469

📂 文件名: WUP2018-F03-Urban_Population.xls

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,"Urban Population at Mid-Year, 1950-2050 (thousands)",Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,Index,"Region, subregion, country or area",Note,Country\ncode,1950.000,1955.000,1960.000,1965.000,1970.000,1975.000,...,2005.000,2010.000,2015.000,2020.000,2025.000,2030.000,2035.000,2040.000,2045.000,2050.000
1,79,China,4,156,65436.582,84639.825,106561.743,130684.595,143513.192,160244.444,...,561983.323,669353.557,775352.918,875075.919,956553.854,1017847.445,1059618.626,1083464.035,1092037.409,1091948.003
2,80,"China, Hong Kong SAR",5,344,1681.846,2121.568,2611.539,3015.435,3397.839,3799.487,...,6827.761,7025.221,7245.701,7547.652,7768.510,7987.249,8126.741,8199.064,8233.792,8253.141
3,81,"China, Macao SAR",6,446,190.373,182.204,159.892,195.462,238.887,236.533,...,482.559,536.969,600.942,651.875,701.381,745.908,783.877,816.675,846.711,875.543
4,82,"China, Taiwan Province of China",NaN,158,2046.275,2623.092,3361.618,4282.804,5360.607,6458.027,...,16339.969,17254.388,18064.348,18802.314,19421.267,19901.735,20210.297,20291.254,20170.795,19917.086

📂 文件名: WUP2018-F04-Rural_Population.xls

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,"Rural Population at Mid-Year, 1950-2050 (thousands)",Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,Index,"Region, subregion, country or area",Note,Country\ncode,1950.000,1955.000,1960.000,1965.000,1970.000,1975.000,...,2005.000,2010.000,2015.000,2020.000,2025.000,2030.000,2035.000,2040.000,2045.000,2050.000
1,79,China,4,156,488982.693,526194.571,551124.400,591877.588,681275.265,760700.639,...,759640.167,690401.545,621675.635,549472.347,482281.843,423334.368,373890.262,334008.779,302323.616,272508.720
2,80,"China, Hong Kong SAR",5,344,292.152,368.535,453.648,473.778,475.273,436.515,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3,81,"China, Macao SAR",6,446,6.110,7.257,7.904,7.769,7.308,5.095,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,82,"China, Taiwan Province of China",NaN,158,5577.085,6399.091,7340.095,8366.922,9332.546,9774.645,...,6262.917,5848.018,5421.407,5015.591,4623.971,4248.973,3890.237,3539.080,3188.498,2853.451

📂 文件名: WUP2018-F05-Total_Population.xls

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,"Total Population at Mid-Year, 1950-2050 (thousands)",Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,Index,"Region, subregion, country or area",Note,Country\ncode,1950.000,1955.000,1960.000,1965.000,1970.000,1975.000,...,2005.000,2010.000,2015.000,2020.000,2025.000,2030.000,2035.000,2040.000,2045.000,2050.000
1,79,China,4,156,554419.275,610834.396,657686.143,722562.183,824788.457,920945.083,...,1321623.490,1359755.102,1397028.553,1424548.266,1438835.697,1441181.813,1433508.888,1417472.814,1394361.025,1364456.723
2,80,"China, Hong Kong SAR","(5) As of 1 July 1997, Hong Kong became a Spec...",344,1973.998,2490.103,3065.187,3489.213,3873.112,4236.002,...,6827.761,7025.221,7245.701,7547.652,7768.510,7987.249,8126.741,8199.064,8233.792,8253.141
3,81,"China, Macao SAR","(6) As of 20 December 1999, Macao became a Spe...",446,196.483,189.461,167.796,203.231,246.195,241.628,...,482.559,536.969,600.942,651.875,701.381,745.908,783.877,816.675,846.711,875.543
4,82,"China, Taiwan Province of China",NaN,158,7623.360,9022.183,10701.713,12649.726,14693.153,16232.672,...,22602.886,23102.406,23485.755,23817.905,24045.238,24150.708,24100.534,23830.334,23359.293,22770.537